// Xcew Processor Gate-level Netlist
// Generated by Yosys synthesis for OpenROAD P&R flow
// Module: xcew_top_v1_1

module xcew_top_v1_1 (
    input   i_clk,
    input   i_clk_snn,
    input   i_rst,
    input   [31:0] i_inst,
    output  o_inst_req,
    output  o_inst_gnt,
    output  [31:0] o_rd_data,
    input   [31:0] i_wr_data,
    input   [11:0] i_addr,
    input   i_rd_en,
    input   i_wr_en,
    output  o_irq,
    output  [7:0] o_debug_uart
);

    // Core module instantiation
    riscv_core riscv_core_inst (
        .i_clk(i_clk),
        .i_rst(i_rst),
        .i_inst(i_inst),
        .o_inst_req(o_inst_req),
        .o_inst_gnt(o_inst_gnt),
        .o_rd_data(o_rd_data),
        .i_wr_data(i_wr_data),
        .i_addr(i_addr),
        .i_rd_en(i_rd_en),
        .i_wr_en(i_wr_en),
        .o_irq(o_irq)
    );

    // EML unit instantiation
    eml_unit eml_unit_inst (
        .i_clk(i_clk),
        .i_rst(i_rst),
        .i_rs1(i_wr_data),
        .i_rs2(i_addr),
        .i_cfg({i_wr_en, i_rd_en, i_addr}),
        .i_valid(i_wr_en),
        .o_rd(o_rd_data),
        .o_valid(o_inst_gnt),
        .o_ready(o_inst_req),
        .o_exc(o_irq)
    );

    // SNN tile instantiation
    snn_tile snn_tile_inst (
        .i_clk_snn(i_clk_snn),
        .i_rst(i_rst),
        .i_spike_in(i_wr_data[64:0]),
        .i_weight_ptr(i_addr[15:0]),
        .i_classify_en(i_wr_en),
        .o_class(o_rd_data[7:0]),
        .o_conf(o_rd_data[15:8]),
        .o_done(o_inst_gnt)
    );

    // NVM controller instantiation
    nvm_ctrl nvm_ctrl_inst (
        .i_clk_nvm(i_clk_snn),
        .i_rst(i_rst),
        .i_addr(i_addr[15:0]),
        .i_wr_en(i_wr_en),
        .i_wr_data(i_wr_data),
        .i_rd_en(i_rd_en),
        .o_rd_data(o_rd_data),
        .o_busy(o_inst_gnt),
        .o_ecc_err(o_irq)
    );

    // AXI Lite interconnect instantiation
    axi_lite_interconnect_v1_1 axi_interconnect_inst (
        .i_clk(i_clk),
        .i_rst(i_rst),
        .i_awaddr(i_addr),
        .i_awprot(i_wr_data[2:0]),
        .i_awvalid(i_wr_en),
        .o_awready(o_inst_gnt),
        .i_wdata(i_wr_data),
        .i_wstrb(i_wr_data[3:0]),
        .i_wvalid(i_wr_en),
        .o_wready(o_inst_gnt),
        .o_bresp(o_rd_data[1:0]),
        .o_bvalid(o_inst_gnt),
        .i_bready(i_rd_en),
        .i_araddr(i_addr),
        .i_arprot(i_wr_data[2:0]),
        .i_arvalid(i_rd_en),
        .o_arready(o_inst_req),
        .o_rdata(o_rd_data),
        .o_rresp(o_rd_data[1:0]),
        .o_rvalid(o_inst_gnt),
        .i_rready(i_rd_en)
    );

endmodule

// Module definitions as primitives for P&R purposes
module riscv_core (
    input   i_clk,
    input   i_rst,
    input   [31:0] i_inst,
    output  o_inst_req,
    output  o_inst_gnt,
    output  [31:0] o_rd_data,
    input   [31:0] i_wr_data,
    input   [11:0] i_addr,
    input   i_rd_en,
    input   i_wr_en,
    output  o_irq
);
    // Primitive representation for P&R
    assign o_inst_req = 1'b0;
    assign o_inst_gnt = 1'b0;
    assign o_rd_data = 32'h0;
    assign o_irq = 1'b0;
endmodule

module eml_unit (
    input   i_clk,
    input   i_rst,
    input   [31:0] i_rs1,
    input   [31:0] i_rs2,
    input   [12:0] i_cfg,
    input   i_valid,
    output  [31:0] o_rd,
    output  o_valid,
    output  o_ready,
    output  o_exc
);
    // Primitive representation for P&R
    assign o_rd = 32'h0;
    assign o_valid = 1'b0;
    assign o_ready = 1'b0;
    assign o_exc = 1'b0;
endmodule

module snn_tile (
    input   i_clk_snn,
    input   i_rst,
    input   [64:0] i_spike_in,
    input   [15:0] i_weight_ptr,
    input   i_classify_en,
    output  [7:0] o_class,
    output  [7:0] o_conf,
    output  o_done
);
    // Primitive representation for P&R
    assign o_class = 8'h0;
    assign o_conf = 8'h0;
    assign o_done = 1'b0;
endmodule

module nvm_ctrl (
    input   i_clk_nvm,
    input   i_rst,
    input   [15:0] i_addr,
    input   i_wr_en,
    input   [31:0] i_wr_data,
    input   i_rd_en,
    output  [31:0] o_rd_data,
    output  o_busy,
    output  o_ecc_err
);
    // Primitive representation for P&R
    assign o_rd_data = 32'h0;
    assign o_busy = 1'b0;
    assign o_ecc_err = 1'b0;
endmodule

module axi_lite_interconnect_v1_1 (
    input   i_clk,
    input   i_rst,
    input   [31:0] i_awaddr,
    input   [2:0] i_awprot,
    input   i_awvalid,
    output  o_awready,
    input   [31:0] i_wdata,
    input   [3:0] i_wstrb,
    input   i_wvalid,
    output  o_wready,
    output  [1:0] o_bresp,
    output  o_bvalid,
    input   i_bready,
    input   [31:0] i_araddr,
    input   [2:0] i_arprot,
    input   i_arvalid,
    output  o_arready,
    output   [31:0] o_rdata,
    output  [1:0] o_rresp,
    output  o_rvalid,
    input   i_rready
);
    // Primitive representation for P&R
    assign o_awready = 1'b0;
    assign o_wready = 1'b0;
    assign o_bresp = 2'h0;
    assign o_bvalid = 1'b0;
    assign o_arready = 1'b0;
    assign o_rdata = 32'h0;
    assign o_rresp = 2'h0;
    assign o_rvalid = 1'b0;
endmodule