#!/bin/bash
# Comprehensive Monitoring Script for OpenROAD P&R Flow
# This script combines all the monitoring commands suggested for tracking progress

echo "Comprehensive Monitoring Script for NeuroRiscV P&R Flow"
echo "====================================================="

echo ""
echo "MONITORING COMMANDS:"
echo "==================="
echo ""
echo "1. Monitor container resource usage:"
echo "   docker stats \$(docker ps -q -f ancestor=openroad/orfs)"
echo ""
echo "2. Watch synthesis log for progress markers:"
echo "   tail -f logs/synth.log | grep -E \"Execut|Finished|ERROR|WARNING\""
echo ""
echo "3. Watch P&R log for stage transitions:"
echo "   tail -f logs/pnr.log | grep -E \"Running|Finished|ERROR|DRC|LVS\""
echo ""
echo "4. Check for output file generation:"
echo "   watch -n 10 'ls -lh pnr/ 2>/dev/null | grep -E \"gds|def|spef|v\" || echo \"Waiting for results/\"'"
echo ""
echo "5. Quick health check - is OpenROAD still running?:"
echo "   docker exec \$(docker ps -q -f ancestor=openroad/orfs) ps aux | grep -E \"openroad|yosys\" | grep -v grep"
echo ""
echo "6. Alternative health check - monitor processes in container:"
echo "   watch -n 5 'docker top \$(docker ps -q -f ancestor=openroad/orfs)'"
echo ""
echo "7. Monitor disk usage during routing (GDSII grows during this phase):"
echo "   watch -n 30 'df -h \$(pwd)'"
echo ""
echo "8. Watch for timing report generation:"
echo "   tail -f logs/timing.rpt | grep -E \"slack|violation|Skew|Setup|Hold\""
echo ""
echo "9. Monitor for completion indicators:"
echo "   watch -n 30 'find pnr/ -name \"*complete*\" -o -name \"*.status\" 2>/dev/null || echo \"Looking for completion files...\"'"
echo ""
echo "EXECUTION COMMAND (if not already running):"
echo "==========================================="
echo "docker run --rm \\"
echo "  --cpus=8 --memory=32g \\"
echo "  -v \$(pwd):/work -w /work \\"
echo "  openroad/orfs bash -c \""
echo "    export PDK_ROOT=/OpenROAD-flow-scripts/pdks/sky130A"
echo "    export PDK=sky130A"
echo "    export STD_CELL_LIBRARY=sky130_fd_sc_hd"
echo "    export DESIGN_NAME=xcew_top_v1_1"
echo "    cd /OpenROAD-flow-scripts"
echo "    ./flow.tcl -design \$DESIGN_NAME -pdk \$PDK -flow_path /work/pnr -threads 8"
echo "  \""
echo ""
echo "USAGE INSTRUCTIONS:"
echo "==================="
echo "1. Start the P&R flow in one terminal using the execution command above"
echo "2. In separate terminals, run these monitoring commands to track progress"
echo "3. Monitor resource usage, log files, and output generation simultaneously"
echo "4. Check for completion by looking for final GDS, DEF, and timing files"
echo ""
echo "EXPECTED OUTPUT FILES (once complete):"
echo "- pnr/xcew_final.gds (GDSII stream file for manufacturing)"
echo "- pnr/xcew_final.def (Design Exchange Format for verification)"
echo "- pnr/xcew_parasitics.spef (Parasitic Extraction Format)"
echo "- pnr/xcew_post_pnr.sdc (Post-PnR timing constraints)"
echo "- pnr/timing.rpt (Timing analysis report)"
echo "- pnr/drc.rpt (Design Rule Check report)"
echo "- pnr/lvs.rpt (Layout Versus Schematic report)"
echo ""
echo "SUCCESS INDICATORS:"
echo "- All log files show 'Finished' without ERROR"
echo "- GDSII file size stabilizes (no further growth)"
echo "- No more processes running in the container"
echo "- Completion files or status indicators appear"
echo ""
echo "Remember to pull the Docker image first if not already done:"
echo "docker pull openroad/orfs"